version: "3.9"

services:
  frontend:
    depends_on:
      - backend 
    # command: tail -F anything

    build:
      context: ./react-frontend
    ports:
      - "5173:5173"

  backend:
    build: ./spring-backend
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/employee_creator
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    command: sh -c 'sleep 30 && java -jar /app/spring-backend-0.0.1-SNAPSHOT.jar'
  db:
    image: mysql:latest
    restart: always
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: employee_creator
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 5s
      retries: 10

volumes:
  mysql-data: