name: Spring Backend Tests

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: employee_creator
          MYSQL_USER: testuser
          MYSQL_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        
    steps:
    - uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: '17'

    - name: Build with Maven
      run: mvn -B package --file ./spring-backend/pom.xml -DskipTests

    - name: Run tests with Maven
      run: mvn test --file ./spring-backend/pom.xml
      
