name: Run tests on push

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build application
      run: |
        cd ./spring-backend
        ./mvnw clean package -DskipTests

    - name: Run tests
      run: |
        cd ./spring-backend
        ./mvnw test
